# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11759c2dc8640333cf7544082f58152cd7ce93a83b334f3a74bb91e4e46344033002fdde93f8dd015e9a1c0ccd34825702e338064c090859faf7572c0b9d12ab

test:
  secret_key_base: cd0133e75ddab88fd671a27e7d6eb58084facf6050abf19fe459518da2efcfb1f0c43cca79914a972c0620fcf058e4208c8941968051b7130502c1294d8fdf2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
